"""empty message

Revision ID: 24e27e6acd8c
Revises: 37ece2930be1
Create Date: 2019-09-19 06:36:59.199247

"""

# revision identifiers, used by Alembic.
revision = '24e27e6acd8c'
down_revision = '37ece2930be1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('group_admin', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'group_admin')
    # ### end Alembic commands ###
