"""empty message

Revision ID: 83bbd5dd3fe8
Revises: 
Create Date: 2019-09-25 12:53:39.969148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83bbd5dd3fe8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USERS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GROUPS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=80), nullable=True),
    sa.Column('group_no_of_members', sa.Integer(), nullable=True),
    sa.Column('group_target', sa.Integer(), nullable=True),
    sa.Column('group_aggr_amount', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MEMBERS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_name', sa.Text(), nullable=True),
    sa.Column('group_name', sa.Text(), nullable=True),
    sa.Column('payment_scheme', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['GROUPS.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MEMBERS')
    op.drop_table('GROUPS')
    op.drop_table('USERS')
    # ### end Alembic commands ###
